### ISSUE TITLE
Destroy all resources gracefully

### ISSUE THREAD

**Issue by kaxil** [astronomer/terraform-google-astronomer-cloud#5]
Figure out the sequence of commands to destroy all the resources.

Some `terraform destroy` commands need to run with `-target` and need `proxy`.

Maybe write a bash script or directly write them in the Makefile.

**Comment by sjmiller609** [comment]
the pipeline script deletes the full deployment successfully, so I believe this is closed. https://github.com/astronomer/terraform-google-astronomer-cloud/blob/master/pipeline/run_terraform.sh
